# Generated by Django 4.1.7 on 2023-03-16 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_searches', models.IntegerField()),
                ('first_search', models.CharField(max_length=200)),
                ('last_search', models.CharField(max_length=200)),
                ('search_text', models.CharField(max_length=200)),
                ('created_at', models.DateField(auto_now=True)),
                ('last_num_searches', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_query', models.CharField(max_length=200)),
                ('search_result_title', models.CharField(max_length=255)),
                ('search_result_summary', models.TextField()),
                ('published_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
