# Generated by Django 4.1.7 on 2023-03-16 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_query', models.CharField(max_length=200)),
                ('search_result_title', models.CharField(max_length=255)),
                ('search_result_summary', models.TextField()),
            ],
        ),
    ]
